[2/2] unlink notification volume is back [SQUASH]
Change-Id: I5712c9bf356f2fcb5826a7ad419f934a2f639ddc

Conflicts:
	res/values/du_strings.xml

Fix FC if opening Audio Settings after enabling DND

edit by maxwen: code improvements

unlink notifications in Audio settings, then return to home, then
enable DND (full silence), then try to open Audio settings

java.lang.IllegalStateException: Cannot call this method while RecyclerView is computing a layout or scrolling

Change-Id: I8b47f3d8094b57400c6ee63bd941eaf5cd5d6408